# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v7

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Evaluate version
        id: eval_version
        run: |
          CLEAN_VERSION=$(yq eval ".project.version" pyproject.toml)
          BUILD_VERSION="${CLEAN_VERSION}.dev${{ github.run_number }}"
          echo "app_version=${CLEAN_VERSION}" >> $GITHUB_OUTPUT
          echo "build_version=${BUILD_VERSION}" >> $GITHUB_OUTPUT

      - name: Print generated versions
        run: |
          echo "Version for Python backend: ${{ steps.eval_version.outputs.build_version }}"
      
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          # required
          client-id: ${{ vars.PROMOTE_CLIENT_ID }}
          private-key: ${{ secrets.PROMOTE_APP_KEY }}
          repositories: |
            kuzma975/ci-test-project-b
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - id: committer
        run: echo "string=${{ steps.app-token.outputs.app-slug }}[bot] <${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>"  >> "$GITHUB_OUTPUT"
      - run: echo "committer string is ${{ steps.committer.outputs.string }}"
      - uses: actions/checkout@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: kuzma975/ci-test-project-b
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: true
          path: project-b
      - name: Update Docker Tag with yq
        run: |
          cd project-b
          # Оновлюємо значення тегу у файлі конфігурації за допомогою yq (без sed!)
          yq -i '.project-b.tag = "${{ steps.eval_version.outputs.build_version }}"' clusters/dev/values.yaml
          
          # Налаштовуємо ім'я бота для гарного відображення в історії Git
          git config user.name "promote-bot[bot]"
          git config user.email "promote-bot[bot]@users.noreply.github.com"
          
          git add clusters/dev/values.yaml
          git commit -m "chore(gitops): bump project-b docker tag to ${{ steps.eval_version.outputs.build_version }}"
          git push origin main
